### PR TITLE
Change map title styling and colors

### LINKED ISSUE #64: Pretty message strings for all maps
Some of our maps don't use colorized message strings. This is nitpicky, I know, but it'd be great if they did. Updating them would require editing the .map file (even in a text editor) and then just running `quemap -bsp -onlyents maps/foo.map`. It'd take a few minutes per map, with unpacking and repacking.

### PR DESCRIPTION
**Pull request by kaadmy**
Might take a bit of time to get the colors down right, this is just my first try at this.

Should close #64 when this is done.

### CODE REVIEW

**Comment by jdolan** [comment]
Hm. Now that I see these.. and because you removed the author name from the Quake2 remakes, I'm wondering if the Quake2 remakes should just be in all green, like Quake2 displayed them?

**Comment by kaadmy** [comment]
I didn't remove the author names from the Quake2 remakes, they just didn't have any in the first place.

**Comment by jdolan** [comment]
Honestly, after thinking on this, and seeing this branch in action, I'm tempted to suggest we go with straight-up green messages for the Quake and Quake2 remakes -- just like Quake2 did.

For original maps, or ports of community maps, we can stick with the colored names, however folks like to have them.

What do you think @kaadmy ?

**Comment by kaadmy** [comment]
I can easily change the remakes to green, which ones are they?

**Comment by jdolan** [comment]
Seriously? lol.

edge
tokays
fragpipe
hallways
pits
lavatomb
slimyplace
warehouse
darkzone

**Pull request closed without merging**
