### PR TITLE
Added new machinegun model

### PR DESCRIPTION
**Pull request by kaadmy**
Added a new Machinegun model, includes .blend file and new world/view/link.cfg files.
May need new textures for this model, although the current ones work good enough.

### CODE REVIEW

**Comment by jdolan** [comment]
quetoo009
quetoo008

Overall, I think this is a great improvement. However, the placement of the model needs some work before we could merge this. You can see in the world view, it's quite low. In the first person view, it's a bit too high and a tad large. In the link view, it should probably nudge forward a hair so as to not intersect qforcer's bicep so much.

A good hint of what's wrong can be gleaned from the diffs in *.cfg here. All of our other models have approximately the same configurations for word, view and link. In order to look correct, this model should have as-close-to neutral world.cfg as possible:

    translate "0.0 0.0 0.0"
    scale "1.0"

And then view.cfg and link.cfg should adjust from there. Basically, re-center / scale the model so that world.cfg can look like the snippet above.

**Comment by kaadmy** [comment]
The world.cfg is already reset, and the link.cfg has minimal changes to align it.
The original model was ~32u higher than zero, so the alignment was off quite a bit.

**Comment by jdolan** [comment]
No, I know that world.cfg is reset. And the model sits far too low. All Quake pickup models have an origin in positive Z. You moved the model down, and so it clearly sits too low in world view now. See the 2nd screenshot: the MG sits far lower than the ammo boxes.

**Comment by kaadmy** [comment]
Ah, didn't notice that, will fix.

**Comment by jdolan** [comment]
Looks pretty good to me. I think there's maybe still some fine tuning for the view.cfg, but this is an improvement over master. Go ahead and squash/merge. Nice work. 👍

**Pull request merged**
