### PR TITLE
Model tweaks

### PR DESCRIPTION
**Pull request by kaadmy**
Did a final pass on all the weapons, they should be correct and lined up now.
Maybe very slight tweaking, but I think they're ready to be squashed and merged.

### CODE REVIEW

**Comment by kaadmy** [comment]
@jdolan can you go through this and see if you noticed anything out of place or whatnot?

**Comment by jdolan** [comment]
@kaadmy Hm, sorry, but quite a few things from 1380013b4e9b7c6d362517cc74e6cf5cf7480f78 were lost in your last commit. I can post screenshots if you like, but if you simply jump between that revision and HEAD, I think you'll see what I'm talking about.

**Comment by kaadmy** [comment]
I think they look okay, but your commit made some weapons just look pretty ugly IMHO.
RL, BFG, SG, and SSG were too far out, at 110 FOV they already looked way too long and covered a lot of the view.

**Comment by jdolan** [comment]
We can tune the view.cfg's some more, but the world.cfg's I had put in place normalized all of the weapons. There are huge discrepancies now which look funny: e.g. the GL is smaller than the MG.

**Comment by kaadmy** [comment]
Well ideally all the weapons should have unique silhouettes so you can distinguish them from each other..
The grenade launcher is probably the worst weapon model right now, since it doesn't really look like any other weapon and it's most shorter and wider.

**Comment by jdolan** [comment]
Agreed, the GL is an outlier. My comments still stand :P

**Pull request closed without merging**
